### ISSUE TITLE
文字列は char* は使わずにstd::stringを使ってください。

### ISSUE THREAD

**Issue by yogomi** [ktadasoliton/file_read_sample#5]
char* はC言語の書き方です。
C言語の世界に居たいのならば良いですが、C言語の世界を堪能するならばポインタのマナーを知ってなければいけません。

例えば、ポインタを渡されたら必ずNULLじゃないかチェックしろとか。

多分そのマナーを覚えるよりもstd::stringを使った方が良いです。

char took_section[512];

こういう文字列配列もstd::stringです。512文字以内に収まらなかった場合とかを気にする必要はありません。

**Comment by yogomi** [comment]
もし、char*をどうしても使いたいようであればポインタならば気をつけなければいけないことをレビューで書きますが、まだいらないよね？

ポインタはポインタで、パケットとかデータ型を扱う時とか使うのだけど、まだちょっとハードル高いかと。

std::string name;
name.c_str();
とかすれば char* を constで取り出せる。std::stringの説明は一回見ておくと良いよ。

http://vivi.dyndns.org/tech/cpp/string.html

**Comment by ktadasoliton** [comment]
stringだけでもいろんなことできるんですね
